/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const AphroditeModel = (props) => {
  const { nodes, materials } = useGLTF("/computer-room-no-glass.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node.geometry}
        material={materials.palette}
      />
    </group>
  );
};

export default AphroditeModel;
useGLTF.preload("/computer-room-no-glass.gltf");
